### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by synesthesiam** [synesthesiam/voice2json#44]
# Development Roadmap for voice2json

## v2.1

- [X] Upgrade to DeepSpeech v0.9
- [X] Automatic language file downloads
- [X] New Kaldi/DeepSpeech profiles (Czech, German, French, Italian, Russian, Swedish)

## v2.2

- [ ] Swap Mycroft Precise for [Raven](https://github.com/rhasspy/rhasspy-wake-raven) (wake word)
- [ ] Swap MaryTTS for [Larynx](https://github.com/rhasspy/larynx) (text to speech)

## v2.3

- [ ] Dynamic grammars for Kaldi models (change active intents for ASR + NLU w/o re-training)
- [ ] Generate slot graphs separately as [Kaldi grammar FSTs](http://kaldi-asr.org/doc/grammar.html)
- [ ] Use word-level confidence values from Kaldi to estimate sentence confidence
- [ ] Investigate acoustic distance between input audio and output sentence as a confidence measure

**Comment by atakangah** [comment]
I was able to build from source on MacOS 14 Sonoma. I can still put up PR for the changes I made to make it work, right?
